name: Auto Label
on:
  pull_request:
    branches:
      - master
jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - name: auto label
        uses: RocketSurgeonsGuild/actions/auto-label@v0.3.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
