name: Auto Label
on:
  pull_request:
    branches:
      - master
jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: auto label
        uses: RocketSurgeonsGuild/actions/auto-label@v0.2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
