name: Auto Label
on:
  pull_request:
    branches:
      - master
jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: auto label
        uses: RocketSurgeonsGuild/actions/auto-label@v0.3.15
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
