name: Auto Label
on:
  pull_request:
    branches:
      - master
jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: auto label
        uses: RocketSurgeonsGuild/actions/auto-label@v0.3.13
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
