name: Auto Label
on:
  pull_request:
    branches:
      - master
jobs:
  auto_label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: auto label
        uses: RocketSurgeonsGuild/actions/auto-label@v0.3.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
