name: Dependabot Commenter

on:
  pull_request_target:
    types:
      - labeled
      - opened
      - reopened
      - closed

jobs:
  comment:
    uses: RocketSurgeonsGuild/actions/dotnet/workflows/dependabot-merge.yml@v0.2.5
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RSG_BOT_TOKEN: ${{ secrets.RSG_BOT_TOKEN }}
