name: Create Milestone and Draft Release

on:
  workflow_call:
    # inputs:
    secrets:
      RSG_BOT_TOKEN:
        required: true
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '0 0 * * 4'

jobs:
  create_milestone_and_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Fetch all history for all tags and branches
        run: git fetch --prune

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Create Milestone
        uses: WyriHaximus/github-action-create-milestone@v1
        with:
          title: v${{ steps.gitversion.outputs.majorMinorPatch }}
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        continue-on-error: true

      - name: sync milestones
        uses: RocketSurgeonsGuild/actions/sync-milestone@v0.3.5
        with:
          default-label: ':sparkles: mysterious'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          generateReleaseNotes: true
          name: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
          tag: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
          token: ${{ secrets.RSG_BOT_TOKEN }}
          draft: true
          commit: ${{ github.base_ref }}
