name: sync-labels
on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/sync-labels.yml
      - .github/labels.yml

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout tools repo
        uses: actions/checkout@v2
        with:
          repository: RocketSurgeonsGuild/.github
          path: .rsg

      - name: merge files
        shell: pwsh
        run: |
          echo (Get-Content -Raw ".github/labels.yml")
          echo (Get-Content -Raw ".rsg/.github/labels.yml")

          Add-Content -Path ".rsg/.github/labels.yml" -Value ("`n")
          Add-Content -Path ".rsg/.github/labels.yml" -Value (Get-Content -Raw ".github/labels.yml")

          echo (Get-Content -Raw ".github/labels.yml")
          echo (Get-Content -Raw ".rsg/.github/labels.yml")

      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v2
        with:
          yaml_file: .rsg/.github/labels.yml
          skip_delete: false
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
